apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: somkiat/service2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 1536Mi
            cpu: 55m
        